### ISSUE TITLE
Aesthetic labels for images

### ISSUE THREAD

**Issue by ZachL1** [Dreemurr-T/BAID#2]
Hi, thank you for your great contribution to the Aesthetics dataset.

The [image_list.csv](https://github.com/Dreemurr-T/BAID/blob/master/image_list.csv) you gave only has links to images and no corresponding aesthetic tags.

**Comment by snk4tr** [comment]
I join the question: will the labels be released? It would be great to have them since they are the most informative and valuable part of the dataset.

**Comment by Dreemurr-T** [comment]
Hi there, I have uploaded the ground-truth labels of the train set. However, since we are currently holding an AIAA competition in CGI2023, we can't release the ground-truth labels of the test set right now. We apologize for the inconvenience. We will upload the labels once the competition is over.

**Comment by Dreemurr-T** [comment]
Hi there, I have uploaded the ground-truth labels of the train set. However, since we are currently holding an AIAA competition in CGI2023, we can't release the ground-truth labels of the test set right now. We apologize for the inconvenience. We will upload the labels once the competition is over.

**Comment by FBehrad** [comment]
> Hi there, I have uploaded the ground-truth labels of the train set. However, since we are currently holding an AIAA competition in CGI2023, we can't release the ground-truth labels of the test set right now. We apologize for the inconvenience. We will upload the labels once the competition is over.

Hi, when will the competition be over?
