### ISSUE TITLE
There are some pictures that are BROKEN

### ISSUE THREAD

**Issue by PolarisLight** [Dreemurr-T/BAID#3]
Firstly, thank you for opensource this dataset.
I downloaded the zip from baidu netdisk, and after unzipping it, I found that some of the images had abnormal file sizes and were unreadable using python. Is this normal?  Do these BROKEN data affect the use of the dataset?

**Comment by Dreemurr-T** [comment]
Greetings. The broken images won't affect the dataset since they're not included in the training/validation/test split. There should be ~100 images broken and you can just ignore them.
