### ISSUE TITLE
list index out of range while running test.py

### ISSUE THREAD

**Issue by omarirfa** [Dreemurr-T/BAID#4]
Hi, 

Thanks for the great work yall have done! The paper was a great read along with the supplementary material! I wanted to test the code out for myself. Unfortunately, I am running into an error while running test.py

![image](https://github.com/Dreemurr-T/BAID/assets/61637151/3aa020bb-8b26-423c-9f56-5f9f72f234dd)

It seems the list index is out of range and as u can see the length of the scores dont match the length of predictions? I am wondering how do i fix this? Should i limit the scores to match the predictions?

I am running this in a conda environment on windows 10.

Edit: Just wanted to add I did download the required weights as per the readme and the dataset

**Comment by omarirfa** [comment]
After looking in the code, it seems this line in test.py is set to:

![image](https://github.com/Dreemurr-T/BAID/assets/61637151/af1533a1-93fb-40dd-bd56-a24514f62fd8)

After looking into BBDataset, I saw that we can change the type to test so it uses the test_set.csv instead of val_set.csv which contains only 3200 images. I changed my code to this in test.py to make it work:

![image](https://github.com/Dreemurr-T/BAID/assets/61637151/83c763c6-bc89-4a51-a9c6-dd8b1a17fb47)


please let me know if this is the correct way to use the code?

**Comment by Dreemurr-T** [comment]
Yes, you should change the type parameter to test the code on the test set. I will correct the code ASAP and thanks a lot for your correction!

**Comment by omarirfa** [comment]
Thanks for your help! I will close this issue!
